/**
 * sitemap.ts — Dynamic XML Sitemap for mickiesoft.lk
 *
 * Lives at `app/sitemap.ts` (outside `[locale]`) so Next.js serves it at
 * the canonical path /sitemap.xml, unreachable by the locale middleware.
 *
 * Data source: data/blog/list/en.json (same JSON used by the /api/blog route).
 * Caching: Next.js caches this Route Handler by default; we set `revalidate`
 * to 3600s (1 hour) so the sitemap refreshes automatically after any new post
 * is added — no manual re-deploy needed.
 *
 * SEO standards met:
 *  - Absolute URLs (https://mickiesoft.lk/...)
 *  - <lastmod> in ISO 8601 format for blog posts
 *  - hreflang alternates for en / si locales
 *  - Excludes /api/, /cms/, drafts, and query-based URLs
 *  - W3C-compliant XML generated by Next.js internals
 */

import type { MetadataRoute } from "next"
import { readJson } from "@/lib/read-json"

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const BASE_URL = "https://mickiesoft.lk"

/** Supported locales — keep in sync with src/i18n/routing.ts */
const LOCALES = ["en", "si"] as const
type Locale = (typeof LOCALES)[number]

// ---------------------------------------------------------------------------
// ISR revalidation — sitemap is re-generated at most once per hour.
// This avoids a heavy file-system read on every request while ensuring
// new blog posts appear in the sitemap within ~60 minutes of publication.
// ---------------------------------------------------------------------------
export const revalidate = 3600

// ---------------------------------------------------------------------------
// Blog post shape (only the fields we need from data/blog/list/en.json)
// ---------------------------------------------------------------------------
interface BlogListItem {
  slug: string
  publishedAt: string // "YYYY-MM-DD"
}

// ---------------------------------------------------------------------------
// Helper: resolve a canonical URL + its locale alternates
// ---------------------------------------------------------------------------
function buildEntry(
  path: string,
  lastModified?: string | Date,
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] = "monthly",
  priority = 0.8
): MetadataRoute.Sitemap[number] {
  const alternateLanguages = LOCALES.reduce<Record<Locale, string>>(
    (acc, locale) => {
      if (locale === "en") {
        acc[locale] = `${BASE_URL}${path}`
      } else {
        const cleanPath = path === "/" ? "" : path
        acc[locale] = `${BASE_URL}/${locale}${cleanPath}`
      }
      return acc
    },
    {} as Record<Locale, string>
  )

  return {
    url: `${BASE_URL}${path}`,
    lastModified: lastModified ?? new Date(),
    changeFrequency,
    priority,
    alternates: {
      languages: alternateLanguages,
    },
  }
}

// ---------------------------------------------------------------------------
// Main sitemap generator
// ---------------------------------------------------------------------------
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // ------------------------------------------------------------------
  // 1. Static / evergreen pages
  // ------------------------------------------------------------------
  const staticEntries: MetadataRoute.Sitemap = [
    buildEntry("/", undefined, "yearly", 1.0),
    buildEntry("/blog", undefined, "weekly", 0.9),
    buildEntry("/solutions/healthcare-app-development", undefined, "monthly", 0.9),
    buildEntry("/solutions/hotel-website-design", undefined, "monthly", 0.9),
  ]

  // ------------------------------------------------------------------
  // 2. Dynamic blog posts — sourced directly from the JSON file.
  //    We use the English list as the canonical slug source; slugs are
  //    language-agnostic (same slug is used for both en and si routes).
  // ------------------------------------------------------------------
  let blogEntries: MetadataRoute.Sitemap = []

  try {
    const posts = await readJson<BlogListItem[]>("blog", "list", "en.json")

    blogEntries = posts
      // Safety guard: skip entries with missing slugs (should not happen in
      // a well-maintained JSON, but protects against accidental draft objects)
      .filter((post) => Boolean(post.slug))
      .map((post) => {
        // publishedAt is "YYYY-MM-DD" — convert to a proper Date for lastmod
        const lastModified = post.publishedAt
          ? new Date(post.publishedAt)
          : new Date()

        return buildEntry(`/blog/${post.slug}`, lastModified, "monthly", 0.7)
      })
  } catch (err) {
    // If the file read fails (e.g. during a cold-start edge case), we still
    // return the static entries so the sitemap is never completely broken.
    console.error("[sitemap] Failed to read blog posts:", err)
  }

  return [...staticEntries, ...blogEntries]
}
